import '../css/output.css'
import '../css/custom-style.css'

import type { Metadata } from 'next'
import Navigation from './_components/Navigation'
import Footer from './_components/Footer'

export const metadata: Metadata = {
  title: 'Practice Chat Bot',
  description: 'Generated by Helvin Rymer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main className='min-h-dvh max-w-full'>
          {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
