import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Practice Chat Bot',
  description: 'Generated by Helvin Rymer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='max-w-full'>
          {children}
        </main>
        </body>
    </html>
  )
}
